name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build static export
        run: |
          npm run build
          npm run export
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project aiassist-ohacv --token ${{ secrets.FIREBASE_TOKEN }}