name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies ignoring peer conflicts
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Build the Next.js app (SSR build)
      - name: Build app
        run: npm run build
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # 5. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      # 6. Deploy to Firebase Hosting with Cloud Functions support
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AIASSIST_OHACV }}
          projectId: aiassist-ohacv
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks